# frozen_string_literal: true

source 'https://rubygems.org'

gem 'faraday', '~> 1.4.0'
gem 'faraday_middleware', '~> 1.0.0'
gem 'open_config', '~> 1.1.0'
gem 'pry', '~> 0.13.1'
gem 'thor', '~> 1.1.0'
gem 'net-scp', '~> 3.0.0'
