root: /root/hiwell
required_files:
  - whitelist.json
  - ops.json
  - banned-ips.json

stages:
  production:
    user: root
    host: minecraft.iskrenkov.com
    docker:
      compose:
        filename: docker-compose-production.yml
