version: '3.9'

services:
  minecraft:
    image: ghcr.io/eiskrenkov/hiwell:1.18.1-spigot
    env_file:
      - .env
    ports:
      - 25565:25565
    volumes:
      - universe:/minecraft/universe

      - ./ops.json:/minecraft/ops.json
      - ./banned-ips.json:/minecraft/banned-ips.json

volumes:
  universe:
