version: '3.9'

services:
  minecraft:
    image: ghcr.io/eiskrenkov/hiwell:1.0.0-spigot-1.18.2
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile.spigot
      args:
        MINECRAFT_VERSION: '1.18.2'
    env_file:
      - .env
    ports:
      - 25565:25565
    volumes:
      - universe:/minecraft/universe

      - ./ops.json:/minecraft/ops.json
      - ./banned-ips.json:/minecraft/banned-ips.json

volumes:
  universe:
