version: '3.9'

services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MINECRAFT_VERSION: '1.17'
    environment:
      JVM_STARTING_MEMORY: 1G
      JVM_MEMORY_LIMIT: 7G
    ports:
      - 25565:25565
    volumes:
      - universe:/minecraft/universe

volumes:
  universe:
