version: '3.9'

services:
  hiwell:
    image: ghcr.io/eiskrenkov/hiwell:spigot-1.20.1
    env_file:
      - .env
    ports:
      - 25565:25565
    volumes:
      - universe:/minecraft/universe

      - /root/hiwell/ops.json:/minecraft/ops.json
      - /root/hiwell/banned-ips.json:/minecraft/banned-ips.json

volumes:
  universe:
