# Step 1
FROM ruby:3.0.0-alpine AS server-download

ARG MINECRAFT_VERSION

WORKDIR /ruby
COPY ruby .

RUN bundle install

RUN chmod +x bin/vanilla-cli && \
    mkdir /downloads && \
    bin/vanilla-cli download_server --version $MINECRAFT_VERSION --destination /downloads

# Step 2
FROM openjdk:17-slim-buster

WORKDIR /minecraft
COPY --from=server-download /downloads/server.jar .

COPY /minecraft .

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

ENTRYPOINT ["/minecraft/entrypoint.sh"]
