version: '3.9'

services:
  minecraft:
    image: ghcr.io/eiskrenkov/hiwell:1.18.1-spigot
    build:
      context: .
      dockerfile: Dockerfile.spigot
      args:
        MINECRAFT_VERSION: '1.18.1'
    env_file:
      - .env
    ports:
      - 25565:25565
    volumes:
      - universe:/minecraft/universe

      - ./whitelist.json:/minecraft/whitelist.json
      - ./ops.json:/minecraft/ops.json
      - ./banned-ips.json:/minecraft/banned-ips.json

volumes:
  universe:
