version: '3.9'

services:
  hiwell:
    image: ghcr.io/eiskrenkov/hiwell:spigot-1.21.1
    env_file:
      - .env
    ports:
      - 25565:25565
    stdin_open: true
    tty: true
    volumes:
      - universe:/minecraft/universe

      - ./whitelist.json:/minecraft/whitelist.json
      - /root/hiwell/ops.json:/minecraft/ops.json
      - /root/hiwell/banned-ips.json:/minecraft/banned-ips.json

volumes:
  universe:
