version: '3.9'

services:
  minecraft:
    build:
      context: .
      args:
        MINECRAFT_VERSION: '1.17'
    ports:
      - 25565:25565
    volumes:
      - worlds_data:/minecraft

volumes:
  worlds_data:
